name: Bug Report
description: File a bug report
labels: [ "Bug" ]
assignees:
  - tobiashein
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help me analyze and fix the issue. I will get back to you as soon as possible.
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Add screenshots (optional)
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I am using the latest version
        - label: I have attached the configuration file
        - label: I have attached a minimal reproducible example      
